/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagement.view;

/**
 *
 * @author USER
 */
public class AddRoomForm extends javax.swing.JFrame {
    
    private hotelmanagement.model.Room editingRoom = null;
    
    public void loadRoomForEdit(hotelmanagement.model.Room r) {
    this.editingRoom = r;
    roomNumberInput.setText(r.getRoomNumber());
    roomTypeInput.setSelectedItem(r.getRoomType());
    roomCapasityInput.setText(String.valueOf(r.getCapacity()));
    roomAdultRateInput.setText(String.valueOf(r.getAdultRate()));
    roomChildRateInput.setText(String.valueOf(r.getChildRate()));
    roomStatusInput.setSelectedItem(r.getStatus());
    addRoomBtn.setText("Update room");
    jLabel1.setText("Update room");
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddRoomForm.class.getName());

    /**
     * Creates new form AddRoomForm
     */
    public AddRoomForm() {
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rate = new javax.swing.JLabel();
        roomAdultRateInput = new javax.swing.JTextField();
        roomCapasityInput = new javax.swing.JTextField();
        addRoomBtn = new javax.swing.JToggleButton();
        roomType1 = new javax.swing.JLabel();
        roomNumberInput = new javax.swing.JTextField();
        roomTypeInput = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        roomStatusInput = new javax.swing.JComboBox<>();
        roomType = new javax.swing.JLabel();
        rate1 = new javax.swing.JLabel();
        roomCapasity = new javax.swing.JLabel();
        roomChildRateInput = new javax.swing.JTextField();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        rate.setForeground(new java.awt.Color(255, 255, 255));
        rate.setText("Adult rate :");

        roomAdultRateInput.addActionListener(this::roomAdultRateInputActionPerformed);

        addRoomBtn.setText("Add room");
        addRoomBtn.addActionListener(this::addRoomBtnActionPerformed);

        roomType1.setForeground(new java.awt.Color(255, 255, 255));
        roomType1.setText("Room Number :");

        roomTypeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Deluxe", "Suite" }));
        roomTypeInput.addActionListener(this::roomTypeInputActionPerformed);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add a room");

        roomStatusInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "OCCUPIED", "MAINTENANCE", "CLEANING" }));

        roomType.setForeground(new java.awt.Color(255, 255, 255));
        roomType.setText("Room Type :");

        rate1.setForeground(new java.awt.Color(255, 255, 255));
        rate1.setText("Child rate :");

        roomCapasity.setForeground(new java.awt.Color(255, 255, 255));
        roomCapasity.setText("Room Capasity :");

        roomChildRateInput.addActionListener(this::roomChildRateInputActionPerformed);

        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("Status :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomType, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomCapasity, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomTypeInput, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roomCapasityInput)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roomType1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 8, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roomChildRateInput)
                            .addComponent(roomAdultRateInput)
                            .addComponent(roomNumberInput)
                            .addComponent(roomStatusInput, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addRoomBtn)
                .addGap(123, 123, 123))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomType1)
                    .addComponent(roomNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomType)
                    .addComponent(roomTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomCapasity)
                    .addComponent(roomCapasityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status)
                    .addComponent(roomStatusInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rate)
                    .addComponent(roomAdultRateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomChildRateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate1))
                .addGap(18, 18, 18)
                .addComponent(addRoomBtn)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomBtnActionPerformed
    Integer id = (editingRoom != null) ? editingRoom.getRoomId() : null;

    hotelmanagement.controller.RoomController.RoomResult result =
            new hotelmanagement.controller.RoomController().saveRoom(
                    id,
                    roomNumberInput.getText(),
                    roomTypeInput.getSelectedItem().toString(),
                    roomCapasityInput.getText(),
                    roomAdultRateInput.getText(),
                    roomChildRateInput.getText(),
                    roomStatusInput.getSelectedItem().toString());

    javax.swing.JOptionPane.showMessageDialog(this, result.message);
    if (result.success) {
        new RoomForm().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_addRoomBtnActionPerformed

    private void roomAdultRateInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomAdultRateInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomAdultRateInputActionPerformed

    private void roomTypeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomTypeInputActionPerformed

    private void roomChildRateInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomChildRateInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomChildRateInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddRoomForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addRoomBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rate;
    private javax.swing.JLabel rate1;
    private javax.swing.JTextField roomAdultRateInput;
    private javax.swing.JLabel roomCapasity;
    private javax.swing.JTextField roomCapasityInput;
    private javax.swing.JTextField roomChildRateInput;
    private javax.swing.JTextField roomNumberInput;
    private javax.swing.JComboBox<String> roomStatusInput;
    private javax.swing.JLabel roomType;
    private javax.swing.JLabel roomType1;
    private javax.swing.JComboBox<String> roomTypeInput;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
