/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagement.view;

/**
 *
 * @author USER
 */
public class BookingForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingForm.class.getName());

    private java.util.List<hotelmanagement.model.Guest> guestList;
    private java.util.List<hotelmanagement.model.Room> roomList;

    /**
     * Creates new form GuestForm
     */
public BookingForm() {
    initComponents();
    setLocationRelativeTo(null);
    loadGuests();
    loadRooms();

    totalInput.setEditable(false);

    roomBox.addActionListener(e -> recalcTotal());
    adultSpinner.addChangeListener(e -> recalcTotal());
    childSpinner.addChangeListener(e -> recalcTotal());
    checkInInput.addPropertyChangeListener("date", e -> recalcTotal());
    checkOutInput.addPropertyChangeListener("date", e -> recalcTotal());
}

private void recalcTotal() {
    hotelmanagement.model.Room r = currentRoom();
    int nights = nightsBetween();
    if (r == null || nights <= 0) {
        totalInput.setText("");
        return;
    }
    int adults = (Integer) adultSpinner.getValue();
    int children = (Integer) childSpinner.getValue();
    double total = new hotelmanagement.controller.BookingController()
            .calculateTotal(nights, adults, children,
                            r.getAdultRate(), r.getChildRate());
    totalInput.setText(String.format("%.2f", total));
}

private void loadRooms() {
    roomBox.removeAllItems();
    roomList = new hotelmanagement.controller.RoomController().getAllRooms();
    for (hotelmanagement.model.Room r : roomList) {
        if ("AVAILABLE".equalsIgnoreCase(r.getStatus())) {
            roomBox.addItem(r.getRoomId() + " - " + r.getRoomNumber()
                    + " (" + r.getRoomType() + " - Adults Rs." + r.getAdultRate()
                    + " / Kids Rs." + r.getChildRate() + ")");
        }
    }
}

private void loadGuests() {
    guestBox.removeAllItems();
    guestList = new hotelmanagement.controller.GuestController().getAllGuests();
    for (hotelmanagement.model.Guest g : guestList) {
        guestBox.addItem(g.getGuestId() + " - " + g.getFirstName() + " " + g.getLastName());
    }
}

private hotelmanagement.model.Room currentRoom() {
    if (roomBox.getSelectedIndex() < 0) return null;
    String sel = roomBox.getSelectedItem().toString();
    for (hotelmanagement.model.Room r : roomList) {
        if (sel.startsWith(r.getRoomId() + " - ")) return r;
    }
    return null;
}

private int nightsBetween() {
    java.util.Date in = checkInInput.getDate();
    java.util.Date out = checkOutInput.getDate();
    if (in == null || out == null) return 0;
    long diff = out.getTime() - in.getTime();
    long days = diff / (1000L * 60 * 60 * 24);
    return days > 0 ? (int) days : 0;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar3 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        createBookingBtn = new javax.swing.JButton();
        guestBox = new javax.swing.JComboBox<>();
        roomBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        paymentMethodBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        checkInInput = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        adultSpinner = new javax.swing.JSpinner();
        childSpinner = new javax.swing.JSpinner();
        checkOutInput = new com.toedter.calendar.JDateChooser();
        totalInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        backBtn.setText("Cancel");
        backBtn.addActionListener(this::backBtnActionPerformed);

        createBookingBtn.setText("Create Booking");
        createBookingBtn.addActionListener(this::createBookingBtnActionPerformed);

        roomBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Booking form");

        paymentMethodBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CARD", "ONLINE" }));
        paymentMethodBox.addActionListener(this::paymentMethodBoxActionPerformed);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Guest :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Room :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Check-in date :");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Check-out date :");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Adults :");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total amount :");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Children :");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Payment method :");

        adultSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));

        childSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));

        totalInput.setEditable(false);
        totalInput.addActionListener(this::totalInputActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkOutInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkInInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createBookingBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guestBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(roomBox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(paymentMethodBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adultSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(childSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guestBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(checkInInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkOutInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(adultSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(childSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(totalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paymentMethodBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBookingBtn)
                    .addComponent(backBtn))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
    new DashboardFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void createBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBookingBtnActionPerformed
    if (guestBox.getSelectedIndex() < 0 || roomBox.getSelectedIndex() < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a guest and a room.");
        return;
    }
    hotelmanagement.model.Room room = currentRoom();
    if (room == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid room.");
        return;
    }
    int guestId = guestList.get(guestBox.getSelectedIndex()).getGuestId();
    int adults   = (Integer) adultSpinner.getValue();
    int children = (Integer) childSpinner.getValue();
    String payment = paymentMethodBox.getSelectedItem().toString();

    hotelmanagement.controller.BookingController.BookingResult result =
            new hotelmanagement.controller.BookingController().bookRoom(
                    guestId, room.getRoomId(),
                    checkInInput.getDate(), checkOutInput.getDate(),
                    adults, children, payment);

    javax.swing.JOptionPane.showMessageDialog(this, result.message);
    if (result.success) {
        new DashboardFrame().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_createBookingBtnActionPerformed

    private void paymentMethodBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentMethodBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentMethodBoxActionPerformed

    private void totalInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner adultSpinner;
    private javax.swing.JButton backBtn;
    private com.toedter.calendar.JDateChooser checkInInput;
    private com.toedter.calendar.JDateChooser checkOutInput;
    private javax.swing.JSpinner childSpinner;
    private javax.swing.JButton createBookingBtn;
    private javax.swing.JComboBox<String> guestBox;
    private com.toedter.calendar.JCalendar jCalendar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> paymentMethodBox;
    private javax.swing.JComboBox<String> roomBox;
    private javax.swing.JTextField totalInput;
    // End of variables declaration//GEN-END:variables
}
