/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagement.view;

/**
 *
 * @author USER
 */
public class RoomForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RoomForm.class.getName());

    /**
     * Creates new form RoomForm
     */
    public RoomForm() {
        initComponents();
        setLocationRelativeTo(null);
        loadRooms();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        room_number_label = new javax.swing.JLabel();
        room_number = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomOverview = new javax.swing.JTable();
        updateRoomBtn = new javax.swing.JButton();
        addRoomBtn = new javax.swing.JButton();
        deleteRoomBtn = new javax.swing.JButton();

        room_number_label.setText("Enter Room Number");

        room_number.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roomOverview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room number", "Room capasity", "Room type", "Room status", "Rate"
            }
        ));
        jScrollPane1.setViewportView(roomOverview);

        updateRoomBtn.setText("Update room");
        updateRoomBtn.addActionListener(this::updateRoomBtnActionPerformed);

        addRoomBtn.setText("Add room");
        addRoomBtn.addActionListener(this::addRoomBtnActionPerformed);

        deleteRoomBtn.setText("Delete room");
        deleteRoomBtn.addActionListener(this::deleteRoomBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteRoomBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addRoomBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateRoomBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateRoomBtn)
                    .addComponent(addRoomBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteRoomBtn)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomBtnActionPerformed
        new AddRoomForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addRoomBtnActionPerformed

    private void deleteRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoomBtnActionPerformed
 int row = roomOverview.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a room first.");
            return;
        }

        String roomNumber = roomOverview.getValueAt(row, 0).toString();

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Delete room " + roomNumber + "?", "Confirm",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        hotelmanagement.controller.RoomController rc =
                new hotelmanagement.controller.RoomController();
        hotelmanagement.model.Room r = rc.getRoomByNumber(roomNumber);

        if (r == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Room not found.");
            return;
        }

        boolean ok = rc.deleteRoom(r.getRoomId());
        if (ok) {
            javax.swing.JOptionPane.showMessageDialog(this, "Room deleted.");
            loadRooms();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Cannot delete — this room may have bookings.");
        }
    }//GEN-LAST:event_deleteRoomBtnActionPerformed

    private void updateRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRoomBtnActionPerformed
        int row = roomOverview.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a room first.");
            return;
        }

        String roomNumber = roomOverview.getValueAt(row, 0).toString();
        hotelmanagement.model.Room r =
                new hotelmanagement.controller.RoomController().getRoomByNumber(roomNumber);

        if (r == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Room not found.");
            return;
        }

        AddRoomForm form = new AddRoomForm();
        form.loadRoomForEdit(r);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateRoomBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RoomForm().setVisible(true));
    }
    
    private void loadRooms() {
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) roomOverview.getModel();
    model.setRowCount(0);
    for (hotelmanagement.model.Room r :
            new hotelmanagement.controller.RoomController().getAllRooms()) {
        model.addRow(new Object[]{
            r.getRoomNumber(), r.getCapacity(), r.getRoomType(),
            r.getStatus(), r.getRate()
        });
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoomBtn;
    private javax.swing.JButton deleteRoomBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable roomOverview;
    private javax.swing.JTextField room_number;
    private javax.swing.JLabel room_number_label;
    private javax.swing.JButton updateRoomBtn;
    // End of variables declaration//GEN-END:variables
}
